apiVersion: v1
kind: Pod
metadata:
  name: echo-resources
spec:
  containers:
    - name: echo
      image: ealen/echo-server
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
