apiVersion: v1
kind: Pod
metadata:
  name: echo-oom
spec:
  containers:
    - name: memory-hog
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]

