# echo-env-demo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-env-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-env-demo
  template:
    metadata:
      labels:
        app: echo-env-demo
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server
          ports:
            - containerPort: 80
          env:
            - name: ENV_NAME
              value: "staging"
