apiVersion: v1
kind: Pod
metadata:
  name: multi-container-demo
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: web
      image: ealen/echo-server
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/shared

    - name: logger
      image: busybox
      command: ['sh', '-c', 'while true; do echo "$(date) log from sidecar" >> /var/log/shared/log.txt; sleep 5; done']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/shared
