apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-autoscale
  template:
    metadata:
      labels:
        app: echo-autoscale
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
