apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: demo-vol
          mountPath: /data
  volumes:
    - name: demo-vol
      persistentVolumeClaim:
        claimName: local-pvc
