apiVersion: v1
kind: Pod
metadata:
  name: echo-prestop
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: echo
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          echo "Pod started";
          while true; do echo "Running..."; sleep 5; done
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                echo "PreStop hook called at $(date)"
      volumeMounts:
        - name: log-volume
          mountPath: /logs
  volumes:
    - name: log-volume
      emptyDir: {}
