apiVersion: v1
kind: Pod
metadata:
  name: echo-prestop
spec:
  terminationGracePeriodSeconds: 30
  volumes:
    - name: log-volume
      emptyDir: {}

  containers:
    - name: echo
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          echo "Pod started"
          while true; do echo "Running..."; sleep 5; done
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                echo "PreStop hook called at $(date)" >> /logs/prestop.log
      volumeMounts:
        - name: log-volume
          mountPath: /logs

    - name: log-watcher
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          while true; do cat /logs/prestop.log || true; sleep 2; done
      volumeMounts:
        - name: log-volume
          mountPath: /logs
