apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-node-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-node-affinity
  template:
    metadata:
      labels:
        app: echo-node-affinity
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: zone
                    operator: In
                    values:
                      - europe
      containers:
        - name: echo-server
          image: ealen/echo-server
          ports:
            - containerPort: 80
