apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-health
  template:
    metadata:
      labels:
        app: echo-health
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
