apiVersion: v1
kind: Pod
metadata:
  name: downward-api-demo
  labels:
    app: echo
    env: dev
  annotations:
    description: "downward API test"
spec:
  containers:
    - name: echo
      image: busybox
      command: [ "sh", "-c", "env && echo '---' && cat /etc/podinfo/* && sleep 3600" ]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
