apiVersion: v1
kind: Pod
metadata:
  name: secure-echo
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
    - name: echo
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
