apiVersion: v1
kind: Pod
metadata:
  name: echo-probes
spec:
  containers:
    - name: echo
      image: hashicorp/http-echo
      args:
        - "-text=probes!"
        - "-listen=:8080"
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
