apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ibm-appconnect-{{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/name: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Values.namespace }}
rules:
{{ $.Files.Get "static/cluster_role_rules.yaml" }}
{{- if eq .Values.operator.installMode "AllNamespaces" }}
# If installMode is AllNamespaces, we should use the cluster role for everything.
{{ $.Files.Get "static/role_rules.yaml" }}
{{- end }}
