kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-appconnect-{{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/name: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: ibm-appconnect
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ibm-appconnect-{{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
