apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-appconnect-leader
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/name: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-appconnect-leader
subjects:
- kind: ServiceAccount
  name: ibm-appconnect
  namespace: {{ .Release.Namespace }}
