{{ if eq .Values.operator.installMode "OwnNamespace" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  creationTimestamp: null
  name: {{ template "ibm-appconnect.namespacedname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/name: {{ template "ibm-appconnect.namespacedname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: ibm-appconnect
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "ibm-appconnect.namespacedname" . }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}
