apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-appconnect
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: ibm-appconnect
    app.kubernetes.io/name: ibm-appconnect
    app.kubernetes.io/managed-by: {{ .Release.Service }}
imagePullSecrets: 
{{- range .Values.operator.imagePullSecrets }}
  - name: {{ . | indent 2}}
{{- end }}
