apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: echo-app
spec:
  serviceName: "echo-service"
  replicas: 3
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: echo
          image: ealen/echo-server
          ports:
            - containerPort: 80
          volumeMounts:
            - name: echo-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: echo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
